ARG NODE_VERSION=20.18.0
#FROM node:${NODE_VERSION}
#FROM node:${NODE_VERSION}-alpine
FROM node:${NODE_VERSION}-slim
WORKDIR /app

ONBUILD COPY package*.json .
ONBUILD RUN npm install 
ONBUILD COPY . .

CMD [ "node", "index.js" ]